### ISSUE TITLE
`npm install freecodecamp-os` returns "Not found"

### ISSUE THREAD

**Issue by PatrickAlphaC** [freeCodeCamp/freeCodeCampOS#158]
**Describe the bug**
[freecodecamp-os](https://registry.npmjs.org/freecodecamp-os) is not defined. 

**To Reproduce**
1. run `npm install freecodecamp-os`
2. You'll see this error:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/freecodecamp-os - Not found
npm ERR! 404 
npm ERR! 404  'freecodecamp-os@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Expected behavior**
The `README.md` says this should work... so I'd expect it to. 

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: iMac
 - OS: MacOS 13.0 (22A380)

**Comment by PatrickAlphaC** [comment]
I think it should be:

```
npm install @freecodecamp/freecodecamp-os
```

Perhaps we update the docs as such?

**Comment by ShaunSHamilton** [comment]
Yes, we can update the docs for this.
