### ISSUE TITLE
Should this be used to host a course at a website? 

### ISSUE THREAD

**Issue by PatrickAlphaC** [freeCodeCamp/freeCodeCampOS#159]
Hi!

Been playing with this tool, and I love the way it works! I'm wondering... Would it make sense to use this as the basis for an online course? I'd be more than happy to have freeCodeCamp host the course, but it seems like a great template for me to get started with.

Let me know!

**Comment by ShaunSHamilton** [comment]
This relies on the [freeCodeCamp - Courses VSCode extension](https://marketplace.visualstudio.com/items?itemName=freeCodeCamp.freecodecamp-courses). So, I am not sure how you would use this for an online course (outside of tools like Gitpod, CodeSpaces, or CodeAlly).

Do you have anything more specific in mind?

**Comment by PatrickAlphaC** [comment]
It looks like you can serve it from a nodejs standpoint, so I was wondering if this was suitable to host on a site.

It _looks_ like it would work pretty well?

**Comment by ShaunSHamilton** [comment]
We are repeating some stuff across platforms (I am talking with you on the forum), but just to be clear:

You can have the client (React) stuff as a website, but the tests are written in Nodejs, and test the OS filesystem. So, you have to host a VM for each client session - see tools listed above.

The client by itself is nothing special - it does nothing interactive with the lessons.

**Comment by PatrickAlphaC** [comment]
Yes!

Sorry! Will continue on the forum. Thanks for the insights.
