### ISSUE TITLE
[Feat] Add a way to cancel tests

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCampOS#232]
Some of the tests on integrated projects take quite a while to run. We could potentially add a way for people to manually stop those running tests.

**Comment by ShaunSHamilton** [comment]
I tried to do this, but the issue always comes down to:

https://github.com/freeCodeCamp/freeCodeCampOS/blob/61ac3250d3418654992f219e419a01b34414ec71/.freeCodeCamp/tooling/test.js#L95

Once the runner hits that `await`, nothing can abort that from being awaited. I tried `AbortController`s, `setInterval`s, and just throwing everywhere, but it does not help once a test is being awaited.

I am sure there is a way to do this, but that will probably require a lot of refactoring to no longer await the `eval`. For now, I am giving up.

**Comment by ShaunSHamilton** [comment]
I tried using a cancel token for this:

```js
() => {
  const token = {};
  let cancel;
  token.promise = new Promise(resolve => {
    cancel = (reason) => {
      token.reason = reason;
      resolve(reason);
    }
    try {
      // Test
    } ...
  };
  return { cancel, token };
}
```

But that does not work. Lastly, my best working method is to purposefully crash the server, and automatically restart it 🙃

**Comment by gikf** [comment]
As far as the functionality to reliably cancel the run, the Web Worker appears to fulfill that requirement with ease.

**Comment by ShaunSHamilton** [comment]
@gikf Thanks. I keep forgetting Web Workers are a thing 😆
