### ISSUE TITLE
Documentation cannot be accessed

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/freeCodeCampOS#277]
**Describe the bug**
Visiting documentation page - https://opensource.freecodecamp.org/freeCodeCampOS/ results in 404 error _Page not found_

**To Reproduce**
1. Go to https://opensource.freecodecamp.org/freeCodeCampOS/
2. See `404` error

**Comment by ShaunSHamilton** [comment]
Thank you. I did not even notice. There are no errors produced in the build output.

We might need to get a site checker going for up-time.
