### ISSUE TITLE
[Bug] Lesson complete congratulations message persists to next lesson

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/freeCodeCampOS#319]
**Describe the bug**
When lesson is completed, the message congratulating completion is still visible after next lesson is loaded.

After running the tests, tests/hints are displayed normally.

I must say it's not necessarily bad, that hints/tests are not visible initially (sometimes it's too hard to resist peeking at them). However the message can give an impression that next lesson is already completed.

**To Reproduce**
1. Go to any course and non-final lesson.
2. Complete lesson so all tests would pass. If tests don't run automatically, run them manually.
3. See next lesson loaded. In the _Tests_ tab there's still the _Congratulations..._ message displayed.

**Expected behavior**
After next lesson is loaded I'd expect the _Congratulations_ message to not be displayed. (And/or hints for new lesson to be visible).

**Comment by ShaunSHamilton** [comment]
We should probably discuss not showing any congratulations message.

Currently, the expected workflow is:
a) Practice Project
  - Pass tests, and just be taken to the next lesson
  - Finish the last lesson, and be taken to landing page
b) Integrated Project
  - Pass tests, and be taken to landing page

I cannot think of a reason to keep the message?

**Comment by gikf** [comment]
Only reason I can think of - to give clear feedback after all tests in lesson pass. But if that's necessary - I'm not sure.
