### ISSUE TITLE
[feat]: hints

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCampOS#322]
**Hints Functionality**

a) Lines of text (HTML) all shown under the `Hints` tab
b) A list revealed item-by-item with clicks of a button (similar to RDB)
c) A list all shown under the `Hints` tab
d) Other

**Comment by moT01** [comment]
I'm not sure we need hints. We kind of already have all the functionality that we have on /learn. The test text says what went wrong, and the console helps debug. There are some differences - e.g. the new RWD shows the test text (hints) one at a time, and they need to be written in a specific order - and they may be a little more dynamic. Maybe I'm not understanding what these would look like. What would be the difference between these hints and the existing test text? Or are you just looking for more/better ways to do things?

I do recall, at one point, suggesting some sort of troubleshooting page for CodeRoad - perhaps these hints could act more like a troubleshooting area. How to get back on track if you did something wrong or something like that. That seems more related to a whole course and not a step though - maybe a separate feature.

**Comment by ShaunSHamilton** [comment]
I suppose I have been writing the tests a bit differently compared to you. The tests are usually explicit in what is needed, as they elaborate the assertions, but sometimes an actual hint might be better.

In my mind the difference is:
> Instructions
> Make the salamander taller than the t-rex.

> Test Text
> You should give the `#salamander` rule set a `height` of `200px`.

> Hint
> The t-rex is `199px` in `height`.
> The `#salamander` rule affects the salamander.

**Comment by ShaunSHamilton** [comment]
What I currently have in 2.0 is:
- Tests are always visible (even before the "Run Tests" button is pushed) - like `/learn`'s current JS+ stuff
- Console is empty until there is something to display, then displays failing assertions
- Hints are always visible - Though, a details thing like this might be better:

<details>
  <summary>Hint 1</summary>
  I am a hint number uno
</details>
<details>
  <summary>Hint 2</summary>
  I am a better hint
</details>

**Comment by QuincyLarson** [comment]
Hi @ShaunSHamilton we could definitely explore adding a separate "hint" functionality. This said, I recommend we start simple and just focus on getting challenges to work the way Tom's Relational Database Cert challenges work – with contextual failing test messages.

IMHO in rare instances where a hint doesn't fit neatly into the text of a test, we should probably just put it in the instructions. This will make the instruction text slightly longer.

**Comment by ShaunSHamilton** [comment]
@QuincyLarson 
> getting challenges to work the way Tom's Relational Database Cert challenges work – with contextual failing test messages.

We already do have this.
